# Saving and loading Datasets From YAML
This notebook showcases how TorchSig datasets can be saved as YAML files and loaded from YAML later for convenience. 
This is useful when trying to share or version control a large dataset so that it can be reproduced exactly across different teams, but without sharing large arrays of data or different dataset creation scripts.

---

## Saving to YAML
The dataset below is saved to a YAML file for use later. 
Since we give a seed to the dataset, the yaml file will store that seed and use it to reproduce the exact data every time we load from the YAML.

In [1]:
from torchsig.utils.defaults import default_dataset
from torchsig.utils.yaml import save_dataset_yaml, load_dataset_yaml
from pathlib import Path

In [2]:
filepath = "./datasets/yaml_test_dataset"
Path(filepath).parent.mkdir(parents=True, exist_ok=True)

In [3]:
dataset = default_dataset(
    seed=42, target_labels=["class_name", "snr_db"], impairment_level=None
)  # basic default dataset used for testing
save_dataset_yaml(filepath, dataset)

In [4]:
print(next(dataset))
print(next(dataset))
print(next(dataset))

(array([ 0.02311219-0.02543635j, -0.07888075+0.02726327j,
        0.05692025-0.10656164j, ...,  0.13700777+0.03362937j,
        0.00722697+0.03663129j,  0.02593248+0.05931827j],
      shape=(262144,), dtype=complex64), ['64qam', np.float64(7.6)])


(array([-0.10525516+0.08490815j, -0.07363532-0.10551274j,
        0.1273497 -0.0326958j , ...,  0.00961168-0.03739209j,
        0.02748841+0.05255114j, -0.03916043+0.0092365j ],
      shape=(262144,), dtype=complex64), ['64ask', np.float64(46.5)])
(array([ 0.09063724-0.01121376j, -0.06297278+0.1473536j ,
       -0.02430215-0.02785327j, ..., -0.12130772-0.12061954j,
       -0.10326934+0.02931302j,  0.10345804-0.11350849j],
      shape=(262144,), dtype=complex64), ['ofdm-256', np.float64(44.9)])


## Loading from YAML
Now we load a copy of the same dataset. Because the copy loads the same random seed from YAML, the values returned below should match the values above.

In [5]:
dataset_copy = load_dataset_yaml(filepath)

In [6]:
print(next(dataset_copy))
print(next(dataset_copy))
print(next(dataset_copy))

(array([ 0.02311219-0.02543635j, -0.07888075+0.02726327j,
        0.05692025-0.10656164j, ...,  0.13700777+0.03362937j,
        0.00722697+0.03663129j,  0.02593248+0.05931827j],
      shape=(262144,), dtype=complex64), ['64qam', np.float64(7.6)])


(array([-0.10525516+0.08490815j, -0.07363532-0.10551274j,
        0.1273497 -0.0326958j , ...,  0.00961168-0.03739209j,
        0.02748841+0.05255114j, -0.03916043+0.0092365j ],
      shape=(262144,), dtype=complex64), ['64ask', np.float64(46.5)])


(array([ 0.09063724-0.01121376j, -0.06297278+0.1473536j ,
       -0.02430215-0.02785327j, ..., -0.12130772-0.12061954j,
       -0.10326934+0.02931302j,  0.10345804-0.11350849j],
      shape=(262144,), dtype=complex64), ['ofdm-256', np.float64(44.9)])
